export { make_background as default };
const make_background =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/make_background.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL21ha2VfYmFja2dyb3VuZC5zdmciLCJpYXQiOjE2MzA1MDkyNzEsImV4cCI6MTk0NTg2OTI3MX0.hWL8o44D37bICLaFPq2xH1sjcipzN-z87kJ4qNE9Emc";

export const make_backgroundwh =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/make_backgroundwh.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL21ha2VfYmFja2dyb3VuZHdoLnN2ZyIsImlhdCI6MTYzMDUwOTI3MywiZXhwIjoxOTQ1ODY5MjczfQ.OjN538G1TFL3UmH1gaxIQjassIsUPk1Qb-KInqOV1X8";
export const play_background =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/play_background.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3BsYXlfYmFja2dyb3VuZC5zdmciLCJpYXQiOjE2MzA1NzU2MTUsImV4cCI6MTk0NTkzNTYxNX0.pyntBKSyI5nwVLPrh2BNs4qXqDZyETbvSvPtoEW1Gbs";
export const play_background_white =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/play_background_white.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3BsYXlfYmFja2dyb3VuZF93aGl0ZS5zdmciLCJpYXQiOjE2MzA1NzU2MjYsImV4cCI6MTk0NTkzNTYyNn0.PEctfKinxOfB910N5uYd3-KuZsO4zmlXuGWiwefdio0";
export const think_background =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/think_background.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3RoaW5rX2JhY2tncm91bmQuc3ZnIiwiaWF0IjoxNjMwNTA5Mjc1LCJleHAiOjE5NDU4NjkyNzV9.OMMaYq3ehbuDpnFLQrKYb9bdnha_ZunzMcuyYIqhM1o";
export const think_background_1 =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/think_background_1.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3RoaW5rX2JhY2tncm91bmRfMS5zdmciLCJpYXQiOjE2MzA1NzU2NDYsImV4cCI6MTk0NTkzNTY0Nn0.r8zOKwpN0OL76sxRC6xifePBtmTL5I4GJtuYdV4sQZ8";
export const wonder_back_white =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/wonder_back_white.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3dvbmRlcl9iYWNrX3doaXRlLnN2ZyIsImlhdCI6MTYzMDU3NTY1NSwiZXhwIjoxOTQ1OTM1NjU1fQ.6aP05eA9-HP9AlajNpiH_suJfMPWnEnYQBszCK4fRQE";
export const wonder_tree_background =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/wonder_tree_background.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3dvbmRlcl90cmVlX2JhY2tncm91bmQuc3ZnIiwiaWF0IjoxNjMwNTc1NjY3LCJleHAiOjE5NDU5MzU2Njd9.KKmW2VJBpO01rsKd7E61PFY4BDQqZod8Mryls04DVlI";

export const left_arrow =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/left_arrow.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL2xlZnRfYXJyb3cuc3ZnIiwiaWF0IjoxNjMwNjU3MDcxLCJleHAiOjE5NDYwMTcwNzF9.3vm9bwUh82TVmBwGENMSKNkDGxz_WASfdw2BOaJvlZQ";
export const make_with_background =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/make_with_background.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL21ha2Vfd2l0aF9iYWNrZ3JvdW5kLnN2ZyIsImlhdCI6MTYzMDY3OTcwNSwiZXhwIjoxOTQ2MDM5NzA1fQ.1qJ9cVL4tAAV2BRldO2ZEsbhJobtmPebHjbn1JE-6QA";
export const make_only =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/make.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL21ha2Uuc3ZnIiwiaWF0IjoxNjMwNjU3MDk0LCJleHAiOjE5NDYwMTcwOTR9.bCkspP-cAm2h1DdcGtDv-VwP-3CFgITq2oqZjWJN52g";
export const makepic =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/makepic.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL21ha2VwaWMuc3ZnIiwiaWF0IjoxNjMwNjU3MTQ3LCJleHAiOjE5NDYwMTcxNDd9._ZNA5Hqp5v9tAJiOuigj6cgEXpB1VIKeSa7JvJHQHhM";
export const navigation_dots =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/navigation_dots.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL25hdmlnYXRpb25fZG90cy5zdmciLCJpYXQiOjE2MzA2NTcxNTgsImV4cCI6MTk0NjAxNzE1OH0.MPfww7e6wsZyEHvPExqZ0hDst5mrfxsGyiCo4EefS3g";

export const play_with_background =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/play_with_background.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3BsYXlfd2l0aF9iYWNrZ3JvdW5kLnN2ZyIsImlhdCI6MTYzMDY3OTM3MywiZXhwIjoxOTQ2MDM5MzczfQ.6rtAkP1wsQVEO6GBD4WWEc1ulEZumsiI6mnO4q_tJSE";

export const play_only =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/play.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3BsYXkuc3ZnIiwiaWF0IjoxNjMwNjU3MjU3LCJleHAiOjE5NDYwMTcyNTd9.z22agFQFG90frf3dvSswzb-A4hZGEpPzp4IBX5pF3mQ";
export const playpic =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/playpic.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3BsYXlwaWMuc3ZnIiwiaWF0IjoxNjMwNjU3MzA4LCJleHAiOjE5NDYwMTczMDh9.z8Cxw5KuBLhqeWMQ8CdjicIf7xV9etcC9mjEvvNpgl0";
export const right_arrow =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/right_arrow.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3JpZ2h0X2Fycm93LnN2ZyIsImlhdCI6MTYzMDY1NzMyMSwiZXhwIjoxOTQ2MDE3MzIxfQ.Rffz9GmKMOfm6QEI8dd5gxu8WhKPMdvBoVbHecFH-vE";
export const think_with_background =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/think_with_background.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3RoaW5rX3dpdGhfYmFja2dyb3VuZC5zdmciLCJpYXQiOjE2MzA2NzkzNTMsImV4cCI6MTk0NjAzOTM1M30.dBjZsN1WyCEQh_c5qxA1y1XAwnnPxFlH197ImNEbi6w";
export const think_book_only =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/think.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3RoaW5rLnN2ZyIsImlhdCI6MTYzMDY1NzIxMSwiZXhwIjoxOTQ2MDE3MjExfQ.p8fOihUyrqwHWdAevipbYB6jgvlqqDS6XVBudYFZlis";
export const thinkpic =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/thinkpic.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3RoaW5rcGljLnN2ZyIsImlhdCI6MTYzMDY1NzE5MSwiZXhwIjoxOTQ2MDE3MTkxfQ.ayKh7nklNp7pirQ5aRRH5pNsujZsB8m6mqrf9f8uLXs";
export const wonder_leaf_only =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/wonder_.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3dvbmRlcl8uc3ZnIiwiaWF0IjoxNjMwNjU3MTY5LCJleHAiOjE5NDYwMTcxNjl9.RKL0IJhxrr75LFpDeHcKb4DSOQX9BXxzCOy6yJEQTqQ";
export const wonder_with_background =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/wonder_with_background.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3dvbmRlcl93aXRoX2JhY2tncm91bmQuc3ZnIiwiaWF0IjoxNjMwNjc5MzMwLCJleHAiOjE5NDYwMzkzMzB9.hjWjRwCQc_juO8zqp2u1gzkqylmbuyOunN22vCMvfes";
export const wonderpic =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/wonderpic.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3dvbmRlcnBpYy5zdmciLCJpYXQiOjE2MzA2NTcxMjIsImV4cCI6MTk0NjAxNzEyMn0.s9YkkSF5gdzarI0789NB5uqDaYzwlCaXBjf_p7zLnlk";
