export { make_background as default };
const make_background =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/make_background.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL21ha2VfYmFja2dyb3VuZC5zdmciLCJpYXQiOjE2MzA1MDkyNzEsImV4cCI6MTk0NTg2OTI3MX0.hWL8o44D37bICLaFPq2xH1sjcipzN-z87kJ4qNE9Emc";

export const make_backgroundwh =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/make_backgroundwh.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL21ha2VfYmFja2dyb3VuZHdoLnN2ZyIsImlhdCI6MTYzMDUwOTI3MywiZXhwIjoxOTQ1ODY5MjczfQ.OjN538G1TFL3UmH1gaxIQjassIsUPk1Qb-KInqOV1X8";
export const play_background =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/play_background.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3BsYXlfYmFja2dyb3VuZC5zdmciLCJpYXQiOjE2MzA1NzU2MTUsImV4cCI6MTk0NTkzNTYxNX0.pyntBKSyI5nwVLPrh2BNs4qXqDZyETbvSvPtoEW1Gbs";
export const play_background_white =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/play_background_white.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3BsYXlfYmFja2dyb3VuZF93aGl0ZS5zdmciLCJpYXQiOjE2MzA1NzU2MjYsImV4cCI6MTk0NTkzNTYyNn0.PEctfKinxOfB910N5uYd3-KuZsO4zmlXuGWiwefdio0";
export const think_background =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/think_background.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3RoaW5rX2JhY2tncm91bmQuc3ZnIiwiaWF0IjoxNjMwNTA5Mjc1LCJleHAiOjE5NDU4NjkyNzV9.OMMaYq3ehbuDpnFLQrKYb9bdnha_ZunzMcuyYIqhM1o";
export const think_background_1 =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/think_background_1.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3RoaW5rX2JhY2tncm91bmRfMS5zdmciLCJpYXQiOjE2MzA1NzU2NDYsImV4cCI6MTk0NTkzNTY0Nn0.r8zOKwpN0OL76sxRC6xifePBtmTL5I4GJtuYdV4sQZ8";
export const wonder_back_white =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/wonder_back_white.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3dvbmRlcl9iYWNrX3doaXRlLnN2ZyIsImlhdCI6MTYzMDU3NTY1NSwiZXhwIjoxOTQ1OTM1NjU1fQ.6aP05eA9-HP9AlajNpiH_suJfMPWnEnYQBszCK4fRQE";
export const wonder_tree_background =
  "https://vxavjjcpsaykzxkhimor.supabase.in/storage/v1/object/sign/private/content/inner_content_background/wonder_tree_background.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcml2YXRlL2NvbnRlbnQvaW5uZXJfY29udGVudF9iYWNrZ3JvdW5kL3dvbmRlcl90cmVlX2JhY2tncm91bmQuc3ZnIiwiaWF0IjoxNjMwNTc1NjY3LCJleHAiOjE5NDU5MzU2Njd9.KKmW2VJBpO01rsKd7E61PFY4BDQqZod8Mryls04DVlI";
